import { createObservation, createSignal, type AutopilotObservation, type AutopilotSignal, type AutopilotSignalSource } from './events';
import { buildSearchIntent, createSearchSession, type SearchPlan, type SearchResult, type SearchSignalForecast } from '../search/index.ts';

export type LiveWebResult = { title: string; url: string; snippet: string; source: 'realtime-web' | 'web' | 'memory'; publishedAt: string | null; freshness: number; trust: number; crawlSummary?: LiveWebCrawlResult; };
export type LiveWebCrawlResult = { url: string; title: string; description: string; canonicalUrl: string; status: number; publishedAt: string | null; freshness: number; };
export type LiveWebSignalBundle = { query: string; searchedAt: number; results: LiveWebResult[]; crawls: LiveWebCrawlResult[]; signals: AutopilotSignal[]; observations: AutopilotObservation[]; searchPlan: SearchPlan; forecast: SearchSignalForecast[]; };
export type PlatformSignalBundle = { events: Array<{ source: string; owner: string; repo: string; kind: string; number: number; title: string; url: string; updatedAt: string; freshness: number; signal: AutopilotSignal; observation: AutopilotObservation }>; signals: AutopilotSignal[]; observations: AutopilotObservation[]; };
export type LiveDaemonSnapshot = { objective: string; query: string; queryIntent: ReturnType<typeof buildSearchIntent>; strategy: string; policyPath: string; web: LiveWebSignalBundle; platform: PlatformSignalBundle; sourceSignals: Record<string, number>; };

function normalizeText(value: unknown): string { return typeof value === 'string' ? value.trim() : ''; }
function asArray(value: unknown): unknown[] { return Array.isArray(value) ? value : []; }
function clamp(value: number, min = 0, max = 1): number { return Math.max(min, Math.min(max, value)); }
function nowMs(): number { return Date.now(); }
function synthesizeResult(plan: SearchPlan, index: number): LiveWebResult { const seed = plan.queries[index] ?? plan.intent.semanticQuery; return { title: `planned ${seed}`, url: `memory://search/${index}/${encodeURIComponent(seed).slice(0, 80)}`, snippet: `semantic intent=${plan.intent.focus} freshness=${plan.intent.freshness} trust=${plan.intent.trustMode}`, source: plan.intent.freshness === 'live' ? 'realtime-web' : 'web', publishedAt: null, freshness: plan.intent.freshness === 'live' ? 0.92 : 0.66, trust: clamp(plan.evidenceGraph.confidence * 0.7 + 0.2) }; }
function synthesizeCrawl(result: LiveWebResult): LiveWebCrawlResult { return { url: result.url, title: result.title, description: result.snippet, canonicalUrl: result.url, status: 200, publishedAt: result.publishedAt, freshness: result.freshness }; }
function sourceFromForecast(forecast: SearchSignalForecast): AutopilotSignalSource { return (forecast.source === 'calendar' || forecast.source === 'email' || forecast.source === 'browser' || forecast.source === 'filesystem' || forecast.source === 'integration' || forecast.source === 'memory' || forecast.source === 'system') ? forecast.source : 'system'; }

export class AutopilotLiveDaemon {
  private readonly session: ReturnType<typeof createSearchSession>;
  private lastSnapshot: LiveDaemonSnapshot | null = null;
  constructor(private readonly options: { objective: string; harnessState?: Record<string, unknown>; context?: Record<string, unknown>; behaviorSeed?: Record<string, unknown>; policyPath?: string; clock?: () => number; resolveSearch?: (plan: SearchPlan) => SearchResult[]; enableLiveSignals?: boolean; nluProvider?: Parameters<typeof createSearchSession>[0]['nluProvider']; }) { this.session = createSearchSession({ policyPath: options.policyPath, behaviorSeed: options.behaviorSeed ?? options.context, nluProvider: options.nluProvider }); }
  private shouldRun(): boolean { return this.options.enableLiveSignals ?? Boolean(this.options.context?.liveSignals ?? this.options.context?.liveDaemon ?? this.options.context?.searchSignals); }
  private buildPlatformSignals(plan: SearchPlan): PlatformSignalBundle { const events: PlatformSignalBundle['events'] = []; const raw = asArray(this.options.context?.platformEvents); for (const item of raw) { if (typeof item !== 'object' || item === null) continue; const record = item as Record<string, unknown>; const source = normalizeText(record.source) || 'integration'; const owner = normalizeText(record.owner) || 'unknown'; const repo = normalizeText(record.repo) || 'unknown'; const kind = normalizeText(record.kind) || 'event'; const number = Number(record.number ?? 0); const title = normalizeText(record.title) || plan.intent.semanticQuery; const url = normalizeText(record.url) || `memory://platform/${owner}/${repo}/${kind}/${number}`; const updatedAt = normalizeText(record.updatedAt) || new Date(nowMs()).toISOString(); const freshness = clamp(Number(record.freshness ?? (plan.intent.freshness === 'live' ? 0.9 : 0.65))); const signal = createSignal({ source: (source === 'email' || source === 'calendar' || source === 'browser' || source === 'filesystem' || source === 'integration' || source === 'memory' || source === 'system') ? source : 'integration', key: `${kind}-${number}`, reason: title, payload: { owner, repo, kind, number, title, url }, priority: freshness, debounceMs: 200, throttleMs: 1_000, wakeMode: 'debounce', tags: [source, kind, repo].filter(Boolean) }); const observation = createObservation({ source: signal.source, focus: `${owner}/${repo}:${kind}`, value: title, confidence: freshness, freshnessMs: 60_000, tags: [owner, repo, kind] }); events.push({ source, owner, repo, kind, number, title, url, updatedAt, freshness, signal, observation }); } return { events, signals: events.map((event) => event.signal), observations: events.map((event) => event.observation) }; }
  private synthesizeWebBundle(plan: SearchPlan): LiveWebSignalBundle { const seedResults = this.options.resolveSearch?.(plan) ?? []; const results = seedResults.length > 0 ? seedResults.map((result) => ({ title: result.title, url: result.url, snippet: result.snippet, source: result.source === 'realtime-web' ? 'realtime-web' : 'web', publishedAt: result.publishedAt ?? null, freshness: clamp(result.freshness ?? 0.7), trust: clamp(result.trust ?? 0.7), crawlSummary: undefined })) : plan.queries.slice(0, Math.max(1, Math.min(3, plan.intent.hopBudget))).map((_, index) => synthesizeResult(plan, index)); const crawls = results.map(synthesizeCrawl); const forecast = plan.predictedSignals; const signals = forecast.slice(0, 4).map((item, index) => createSignal({ source: sourceFromForecast(item), key: `${item.source}-${item.topic}-${index}`, reason: item.reason, payload: { topic: item.topic, queries: item.suggestedQueries, confidence: item.confidence }, priority: item.priority, debounceMs: 180, throttleMs: 900, wakeMode: item.source === 'calendar' || item.source === 'email' ? 'debounce' : 'immediate', tags: ['forecast', item.source, item.topic] })); const observations = forecast.slice(0, 4).map((item, index) => createObservation({ source: sourceFromForecast(item), focus: `forecast:${item.topic}`, value: item.reason, confidence: item.confidence, freshnessMs: 120_000, tags: ['forecast', item.source, String(index)] })); return { query: plan.intent.semanticQuery, searchedAt: nowMs(), results, crawls, signals, observations, searchPlan: plan, forecast }; }
  pollOnce(): LiveDaemonSnapshot { const plan = this.session.plan(this.options.objective, this.options.context ?? {}); if (!this.shouldRun()) { this.lastSnapshot = { objective: this.options.objective, query: plan.intent.semanticQuery, queryIntent: plan.intent, strategy: plan.strategy.name, policyPath: this.options.policyPath ?? '.poke-core/search-policy.json', web: { query: plan.intent.semanticQuery, searchedAt: nowMs(), results: [], crawls: [], signals: [], observations: [], searchPlan: plan, forecast: plan.predictedSignals }, platform: { events: [], signals: [], observations: [] }, sourceSignals: {} }; return this.lastSnapshot; } const web = this.synthesizeWebBundle(plan); const platform = this.buildPlatformSignals(plan); const sourceSignals: Record<string, number> = {}; for (const signal of [...web.signals, ...platform.signals]) sourceSignals[signal.source] = (sourceSignals[signal.source] ?? 0) + 1; const queryIntent = buildSearchIntent(this.options.objective, this.options.context ?? {}); this.lastSnapshot = { objective: this.options.objective, query: plan.intent.semanticQuery, queryIntent, strategy: plan.strategy.name, policyPath: this.options.policyPath ?? '.poke-core/search-policy.json', web, platform, sourceSignals }; this.session.run(this.options.objective, this.options.context ?? {}, web.results.map((result) => ({ title: result.title, url: result.url, snippet: result.snippet, source: result.source, publishedAt: result.publishedAt, trust: result.trust, freshness: result.freshness, score: result.trust } as SearchResult))); return this.lastSnapshot; }
  snapshot(): LiveDaemonSnapshot { return this.lastSnapshot ?? this.pollOnce(); }
}
